apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: sealed-secrets
  chartRepoUrl: https://bitnami-labs.github.io/sealed-secrets
  chartVersion: 1.13.2
  releaseName: sealed-secrets
  releaseNamespace: sealed-secrets

resources:
  - namespace.yaml